stages:
  - build

variables:
  DB_NAME: UserDB
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: localhost
  DB_PORT: 5432
  DJANGO_SETTINGS_MODULE: "UserService.settings"

before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

services:
  - postgres:latest

build:
  stage: test
  script:
    - python manage.py test